config/routes.rb
Rails.application.routes.draw do
  resources :docs
  
  authenticated :user do
    root 'docs#index', as: 'authenticated_root'
  end
  
  root 'welcome#index'
  
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/doc.rb
class Doc < ActiveRecord::Base
    validates :title, presence: true, length: { minimum: 3 }
    validates :content, presence: true, length: { minimum: 3 }
    
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
    before_action :find_doc, only: [:show, :edit, :destroy, :update]
    
    def index
        @user = current_user
        
        # @docs = @user.docs.all.order("created_at DESC")    
        @docs = Doc.where(user_id: current_user)
    end
    
    def show
        @doc = Doc.find(params[:id])
    end
    
    def new
        if current_user
            @doc = current_user.docs.build
        else
            redirect_to root_path
        end
    end
    
    def create
        @doc = current_user.docs.build(doc_params)
        
        if @doc.save
            flash[:success] = 'File succesfully created'
            redirect_to @doc
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @doc.update(doc_params)
            flash[:success] = 'File succesfully updated'
            redirect_to @doc
        else
            render 'edit'
        end
    end
    
    def destroy
        @doc.destroy
        if @doc.destroy
            flash[:success] = 'File deleted succesfully'
            redirect_to docs_path
        end
    end
    
    private
        def find_doc
            @doc = Doc.find(params[:id])
        end
        
        def doc_params
            params.require(:doc).permit(:title, :content)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/index.html.slim
.container
    h1.hero-heading Contacts

app/views/docs/_form.html.slim
= simple_form_for @doc do |f|
    = f.input :title
    = f.input :content
    = f.button :submit

app/views/docs/edit.html.slim
.container
    h1.hero-heading Edit file
    
    = render 'form'
    
    = link_to 'Cancel', doc_path, class: 'btn btn-default'

app/views/docs/index.html.slim
.container
    = render 'layouts/messages'

    h1.hero-heading All files

    table
        thead
            tr
                th Title
                th Content
                th Created
                th Updated
                th Edit
                th Delete
        tbody
            - @docs.each do |doc|
                tr
                    td = link_to doc.title, doc_path(doc)
                    td = truncate(doc.content, length: 50)
                    td = time_ago_in_words(doc.created_at)
                    td = time_ago_in_words(doc.updated_at)
                    td = link_to 'Edit', edit_doc_path(doc), class: 'edit-btn'
                    td = link_to 'Delete', doc_path(doc), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete-btn'
            
    - if current_user        
        .actions
            = link_to fa_icon('plus') + ' Add New File', new_doc_path, class: 'add-btn'

app/views/docs/new.html.slim
.container
    h1.hero-heading New file
    
    = render 'form'

app/views/docs/show.html.slim
.container
    
    = render 'layouts/messages'

    h1.hero-heading= @doc.title
    p.main-text = @doc.content
    
    hr
    
    .show-page-actions
        = link_to 'Edit', edit_doc_path(@doc), class: 'edit-btn'
        = link_to 'Delete', doc_path(@doc), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete-btn'
    
    .file-info
        p
            small = 'Created at: ' + time_ago_in_words(@doc.created_at)
        p
            small = 'Updated at: ' + time_ago_in_words(@doc.updated_at)

app/views/layouts/_messages.html.slim
- if flash[:success]
    .inside
        .in-inside
            - flash.each do |name, msg|
                .alert-msg 
                    = msg

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta content="width=device-width, initial-scale=1.0" name="viewport" /
    title FILEMANAGER
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar
      .container
        ul.left-nav
          li
            a href="/" = image_tag("logo.png")
        ul.right-nav
          li= link_to 'All Files', docs_path, class: params[:action] == 'index' && params[:controller] == 'docs' ? 'active' : ''
          - if current_user
            li= link_to 'New File', new_doc_path, class: params[:action] == 'new' && params[:controller] == 'docs' ? 'active' : ''
            li= link_to 'Log Out', destroy_user_session_path, method: :delete
          - else
            li= link_to 'Sign Up', new_user_registration_path, class: params[:action] == 'new' && params[:controller] == 'devise/registrations' ? 'active' : ''
            li= link_to 'Sign In', new_user_session_path, class: params[:action] == 'new' && params[:controller] == 'devise/sessions' ? 'active' : ''
    p.notice= notice
    p.alert= alert
    = yield

app/views/welcome/index.html.slim
.header
    .header--hero-text
        h1.hero-heading FileManager

.container
    .col-3
        h1.hero-heading Upload files
        p.justify It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
    .col-3
        h1.hero-heading Share files
        p.justify Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vel eros sem. Donec id diam interdum, fringilla neque mattis, iaculis turpis. In accumsan et nisi a imperdiet. Ut convallis a leo elementum varius. Nulla tempus tellus scelerisque rutrum tempor. Quisque pharetra iaculis vehicula. Donec nisl dolor, ornare quis finibus ac, condimentum id turpis. Duis ut pulvinar nibh, eu varius sapien. Aenean vitae arcu dui. Duis rhoncus at velit quis sollicitudin. Proin a imperdiet tortor, eget egestas tortor. Duis vel erat libero. Vivamus vel facilisis purus.
    .col-3
        h1.hero-heading Archive files
        p.justify It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).

.space